import type { LucideIcon } from "lucide-react";
import {
  Armchair,
  AudioLines,
  Baby,
  BatteryCharging,
  BookOpen,
  Brain,
  Caravan,
  ClipboardList,
  CookingPot,
  Cross,
  Droplet,
  Image,
  Info,
  LogIn,
  MapPin,
  Music,
  Package,
  Palmtree,
  Shield,
  ShoppingBag,
  ShowerHead,
  Sparkles,
  SquareParking,
  Sprout,
  Tent,
  TentTree,
  Toilet,
  Trees,
  Users,
  Utensils,
  Waves,
  Wine,
} from "lucide-react";

/** Maps DB category `icon` strings to lucide components. */
export const ICONS: Record<string, LucideIcon> = {
  music: Music,
  image: Image,
  wine: Wine,
  caravan: Caravan,
  tent: Tent,
  "battery-charging": BatteryCharging,
  "cooking-pot": CookingPot,
  droplet: Droplet,
  palmtree: Palmtree,
  cross: Cross,
  utensils: Utensils,
  "tent-tree": TentTree,
  info: Info,
  "shopping-bag": ShoppingBag,
  "square-parking": SquareParking,
  shield: Shield,
  "shower-head": ShowerHead,
  package: Package,
  toilet: Toilet,
  "log-in": LogIn,
  "clipboard-list": ClipboardList,
  users: Users,
  "audio-lines": AudioLines,
  brain: Brain,
  baby: Baby,
  "book-open": BookOpen,
  armchair: Armchair,
  sparkles: Sparkles,
  waves: Waves,
  sprout: Sprout,
  trees: Trees,
};

export function iconFor(name: string | null): LucideIcon {
  return (name && ICONS[name]) || MapPin;
}
