import SwiftUI

/// Watch parity of the iOS `ShareView` / web `/share`: a QR a friend points their
/// phone at. The encoded link (`AppLinks.qr` → `/get`) routes the scanner — iPhone →
/// App Store, anything else → the web app. watchOS has no CoreImage, so unlike iOS
/// (runtime `QRCode` via CIFilter) the code is a pre-baked asset (`ShareQR`,
/// regenerated by `scripts/build_share_qr.py` whenever `AppLinks.qr` changes). No
/// native share sheet — handing off a URL from the watch isn't useful.
///
/// The QR comes first so it's fully on screen without scrolling; the copy sits below
/// in small type. Tapping the QR opens `WatchQRFullView` — a big, easy-to-scan version
/// on a full cream field. A `NavigationStack` + `cancellationAction` gives a compact
/// close button instead of watchOS' oversized default sheet-dismiss circle.
struct WatchShareView: View {
    @EnvironmentObject var settings: Settings
    @Environment(\.dismiss) private var dismiss
    @State private var showFullQR = false

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(spacing: 6) {
                    // The PNG is already a cream card (baked quiet zone); clip it to
                    // rounded corners directly — a separate padded background let the
                    // square PNG corners poke past the rounding. Tap → full-screen QR.
                    Button { showFullQR = true } label: {
                        Image("ShareQR")
                            .interpolation(.none)       // keep the modules crisp when scaled
                            .resizable()
                            .scaledToFit()
                            .frame(maxWidth: 100)
                            .clipShape(RoundedRectangle(cornerRadius: 6))
                    }
                    .buttonStyle(.plain)

                    Text(L.t("share.title", settings.locale))
                        .font(.system(size: 14, weight: .bold, design: .rounded))
                        .foregroundStyle(Theme.cream)
                        .padding(.top, 6)
                    Text(L.t("share.body", settings.locale))
                        .font(.system(size: 10))
                        .foregroundStyle(Theme.cream.opacity(0.8))
                        .multilineTextAlignment(.center)
                        .fixedSize(horizontal: false, vertical: true)
                }
                .frame(maxWidth: .infinity)
                .padding(.horizontal, 6)
                .padding(.top, -10)     // pull the QR up under the close button
                .padding(.bottom, 10)
            }
            .background(Theme.ink)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button { dismiss() } label: {
                        Image(systemName: "xmark")
                            .font(.system(size: 12, weight: .bold))
                            .foregroundStyle(Theme.cream.opacity(0.9))
                            .frame(width: 26, height: 26)
                            .background(.black.opacity(0.3), in: Circle())
                    }
                    .buttonStyle(.plain)
                }
            }
        }
        // Full-screen overlay (not a sheet): a sheet's NavigationStack insets the
        // content so the QR can't grow; an overlay gets the whole screen.
        .overlay {
            if showFullQR { FullQRView(onClose: { showFullQR = false }) }
        }
    }
}

/// The QR blown up to fill the screen for an easy scan, on a full cream field so the
/// quiet zone is generous. A fixed top band holds the close button, and the QR is
/// pinned below it — so the X never overlaps the code no matter the watch size.
private struct FullQRView: View {
    let onClose: () -> Void

    var body: some View {
        GeometryReader { geo in
            let topBand: CGFloat = 54                                   // bezel + close button
            let side = min(geo.size.width - 20, geo.size.height - topBand - 12)
            ZStack(alignment: .topLeading) {
                Theme.cream
                Image("ShareQR")
                    .interpolation(.none)
                    .resizable()
                    .scaledToFit()
                    .frame(width: side, height: side)
                    .position(x: geo.size.width / 2, y: topBand + side / 2)
                Button(action: onClose) {
                    Image(systemName: "xmark")
                        .font(.system(size: 13, weight: .bold))
                        .foregroundStyle(Theme.ink.opacity(0.6))
                        .frame(width: 30, height: 30)
                        .background(Theme.ink.opacity(0.12), in: Circle())
                }
                .buttonStyle(.plain)
                .padding(.leading, 8)
                .padding(.top, 24)
            }
        }
        .ignoresSafeArea()
    }
}
