import type { Metadata } from "next";
import { GetRedirect } from "@/components/GetRedirect";
import { LANDING_IMG_V } from "@/lib/landing-version";

// /get is the URL the share QR / share sheet hands around, so it carries the
// richest metadata: the shared 1200×630 OpenGraph card (the /app showcase card,
// generated by pwa/scripts/build_landing_images.py → public/landing/og.png) plus
// title/description/Twitter card for the best preview when re-shared.
const title = "Guide for MANAS 2026 — nem hivatalos fesztivál app";
const description =
  "Teljes időrend, élő most-megy nézet a MANAS 2026-hoz. iPhone-on az App Store nyílik, minden máson a WebApp.";
// ?v= busts scraper/browser caches whenever the card is regenerated (same as /app).
const ogImage = {
  url: `/landing/og.png?v=${LANDING_IMG_V}`,
  width: 1200,
  height: 630,
  alt: "Guide for MANAS 2026",
};

export const metadata: Metadata = {
  title,
  description,
  openGraph: {
    type: "website",
    siteName: "Guide for MANAS 2026",
    title,
    description,
    url: "/get",
    locale: "hu_HU",
    alternateLocale: "en_US",
    images: [ogImage],
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
    images: [ogImage.url],
  },
};

export default function GetPage() {
  return <GetRedirect />;
}
